# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dyk/Projects/hardware_driver_lib

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dyk/Projects/hardware_driver_lib

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dyk/Projects/hardware_driver_lib/CMakeFiles /home/dyk/Projects/hardware_driver_lib//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dyk/Projects/hardware_driver_lib/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named hardware_driver_uninstall

# Build rule for target.
hardware_driver_uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hardware_driver_uninstall
.PHONY : hardware_driver_uninstall

# fast build rule for target.
hardware_driver_uninstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hardware_driver_uninstall.dir/build.make CMakeFiles/hardware_driver_uninstall.dir/build
.PHONY : hardware_driver_uninstall/fast

#=============================================================================
# Target rules for targets named hardware_driver_canfd

# Build rule for target.
hardware_driver_canfd: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hardware_driver_canfd
.PHONY : hardware_driver_canfd

# fast build rule for target.
hardware_driver_canfd/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hardware_driver_canfd.dir/build.make CMakeFiles/hardware_driver_canfd.dir/build
.PHONY : hardware_driver_canfd/fast

#=============================================================================
# Target rules for targets named example_event_motor_bus

# Build rule for target.
example_event_motor_bus: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example_event_motor_bus
.PHONY : example_event_motor_bus

# fast build rule for target.
example_event_motor_bus/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_event_motor_bus.dir/build.make CMakeFiles/example_event_motor_bus.dir/build
.PHONY : example_event_motor_bus/fast

#=============================================================================
# Target rules for targets named example_motor_callback

# Build rule for target.
example_motor_callback: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example_motor_callback
.PHONY : example_motor_callback

# fast build rule for target.
example_motor_callback/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_motor_callback.dir/build.make CMakeFiles/example_motor_callback.dir/build
.PHONY : example_motor_callback/fast

#=============================================================================
# Target rules for targets named example_motor_observer

# Build rule for target.
example_motor_observer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example_motor_observer
.PHONY : example_motor_observer

# fast build rule for target.
example_motor_observer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_motor_observer.dir/build.make CMakeFiles/example_motor_observer.dir/build
.PHONY : example_motor_observer/fast

#=============================================================================
# Target rules for targets named example_motor_zero_position

# Build rule for target.
example_motor_zero_position: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example_motor_zero_position
.PHONY : example_motor_zero_position

# fast build rule for target.
example_motor_zero_position/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_motor_zero_position.dir/build.make CMakeFiles/example_motor_zero_position.dir/build
.PHONY : example_motor_zero_position/fast

examples/example_event_motor_bus.o: examples/example_event_motor_bus.cpp.o
.PHONY : examples/example_event_motor_bus.o

# target to build an object file
examples/example_event_motor_bus.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_event_motor_bus.dir/build.make CMakeFiles/example_event_motor_bus.dir/examples/example_event_motor_bus.cpp.o
.PHONY : examples/example_event_motor_bus.cpp.o

examples/example_event_motor_bus.i: examples/example_event_motor_bus.cpp.i
.PHONY : examples/example_event_motor_bus.i

# target to preprocess a source file
examples/example_event_motor_bus.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_event_motor_bus.dir/build.make CMakeFiles/example_event_motor_bus.dir/examples/example_event_motor_bus.cpp.i
.PHONY : examples/example_event_motor_bus.cpp.i

examples/example_event_motor_bus.s: examples/example_event_motor_bus.cpp.s
.PHONY : examples/example_event_motor_bus.s

# target to generate assembly for a file
examples/example_event_motor_bus.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_event_motor_bus.dir/build.make CMakeFiles/example_event_motor_bus.dir/examples/example_event_motor_bus.cpp.s
.PHONY : examples/example_event_motor_bus.cpp.s

examples/example_motor_callback.o: examples/example_motor_callback.cpp.o
.PHONY : examples/example_motor_callback.o

# target to build an object file
examples/example_motor_callback.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_motor_callback.dir/build.make CMakeFiles/example_motor_callback.dir/examples/example_motor_callback.cpp.o
.PHONY : examples/example_motor_callback.cpp.o

examples/example_motor_callback.i: examples/example_motor_callback.cpp.i
.PHONY : examples/example_motor_callback.i

# target to preprocess a source file
examples/example_motor_callback.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_motor_callback.dir/build.make CMakeFiles/example_motor_callback.dir/examples/example_motor_callback.cpp.i
.PHONY : examples/example_motor_callback.cpp.i

examples/example_motor_callback.s: examples/example_motor_callback.cpp.s
.PHONY : examples/example_motor_callback.s

# target to generate assembly for a file
examples/example_motor_callback.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_motor_callback.dir/build.make CMakeFiles/example_motor_callback.dir/examples/example_motor_callback.cpp.s
.PHONY : examples/example_motor_callback.cpp.s

examples/example_motor_observer.o: examples/example_motor_observer.cpp.o
.PHONY : examples/example_motor_observer.o

# target to build an object file
examples/example_motor_observer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_motor_observer.dir/build.make CMakeFiles/example_motor_observer.dir/examples/example_motor_observer.cpp.o
.PHONY : examples/example_motor_observer.cpp.o

examples/example_motor_observer.i: examples/example_motor_observer.cpp.i
.PHONY : examples/example_motor_observer.i

# target to preprocess a source file
examples/example_motor_observer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_motor_observer.dir/build.make CMakeFiles/example_motor_observer.dir/examples/example_motor_observer.cpp.i
.PHONY : examples/example_motor_observer.cpp.i

examples/example_motor_observer.s: examples/example_motor_observer.cpp.s
.PHONY : examples/example_motor_observer.s

# target to generate assembly for a file
examples/example_motor_observer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_motor_observer.dir/build.make CMakeFiles/example_motor_observer.dir/examples/example_motor_observer.cpp.s
.PHONY : examples/example_motor_observer.cpp.s

examples/example_motor_zero_position.o: examples/example_motor_zero_position.cpp.o
.PHONY : examples/example_motor_zero_position.o

# target to build an object file
examples/example_motor_zero_position.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_motor_zero_position.dir/build.make CMakeFiles/example_motor_zero_position.dir/examples/example_motor_zero_position.cpp.o
.PHONY : examples/example_motor_zero_position.cpp.o

examples/example_motor_zero_position.i: examples/example_motor_zero_position.cpp.i
.PHONY : examples/example_motor_zero_position.i

# target to preprocess a source file
examples/example_motor_zero_position.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_motor_zero_position.dir/build.make CMakeFiles/example_motor_zero_position.dir/examples/example_motor_zero_position.cpp.i
.PHONY : examples/example_motor_zero_position.cpp.i

examples/example_motor_zero_position.s: examples/example_motor_zero_position.cpp.s
.PHONY : examples/example_motor_zero_position.s

# target to generate assembly for a file
examples/example_motor_zero_position.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_motor_zero_position.dir/build.make CMakeFiles/example_motor_zero_position.dir/examples/example_motor_zero_position.cpp.s
.PHONY : examples/example_motor_zero_position.cpp.s

src/bus/canfd_bus_impl.o: src/bus/canfd_bus_impl.cpp.o
.PHONY : src/bus/canfd_bus_impl.o

# target to build an object file
src/bus/canfd_bus_impl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hardware_driver_canfd.dir/build.make CMakeFiles/hardware_driver_canfd.dir/src/bus/canfd_bus_impl.cpp.o
.PHONY : src/bus/canfd_bus_impl.cpp.o

src/bus/canfd_bus_impl.i: src/bus/canfd_bus_impl.cpp.i
.PHONY : src/bus/canfd_bus_impl.i

# target to preprocess a source file
src/bus/canfd_bus_impl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hardware_driver_canfd.dir/build.make CMakeFiles/hardware_driver_canfd.dir/src/bus/canfd_bus_impl.cpp.i
.PHONY : src/bus/canfd_bus_impl.cpp.i

src/bus/canfd_bus_impl.s: src/bus/canfd_bus_impl.cpp.s
.PHONY : src/bus/canfd_bus_impl.s

# target to generate assembly for a file
src/bus/canfd_bus_impl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hardware_driver_canfd.dir/build.make CMakeFiles/hardware_driver_canfd.dir/src/bus/canfd_bus_impl.cpp.s
.PHONY : src/bus/canfd_bus_impl.cpp.s

src/driver/gripper_driver_impl.o: src/driver/gripper_driver_impl.cpp.o
.PHONY : src/driver/gripper_driver_impl.o

# target to build an object file
src/driver/gripper_driver_impl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hardware_driver_canfd.dir/build.make CMakeFiles/hardware_driver_canfd.dir/src/driver/gripper_driver_impl.cpp.o
.PHONY : src/driver/gripper_driver_impl.cpp.o

src/driver/gripper_driver_impl.i: src/driver/gripper_driver_impl.cpp.i
.PHONY : src/driver/gripper_driver_impl.i

# target to preprocess a source file
src/driver/gripper_driver_impl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hardware_driver_canfd.dir/build.make CMakeFiles/hardware_driver_canfd.dir/src/driver/gripper_driver_impl.cpp.i
.PHONY : src/driver/gripper_driver_impl.cpp.i

src/driver/gripper_driver_impl.s: src/driver/gripper_driver_impl.cpp.s
.PHONY : src/driver/gripper_driver_impl.s

# target to generate assembly for a file
src/driver/gripper_driver_impl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hardware_driver_canfd.dir/build.make CMakeFiles/hardware_driver_canfd.dir/src/driver/gripper_driver_impl.cpp.s
.PHONY : src/driver/gripper_driver_impl.cpp.s

src/driver/motor_driver_impl.o: src/driver/motor_driver_impl.cpp.o
.PHONY : src/driver/motor_driver_impl.o

# target to build an object file
src/driver/motor_driver_impl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hardware_driver_canfd.dir/build.make CMakeFiles/hardware_driver_canfd.dir/src/driver/motor_driver_impl.cpp.o
.PHONY : src/driver/motor_driver_impl.cpp.o

src/driver/motor_driver_impl.i: src/driver/motor_driver_impl.cpp.i
.PHONY : src/driver/motor_driver_impl.i

# target to preprocess a source file
src/driver/motor_driver_impl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hardware_driver_canfd.dir/build.make CMakeFiles/hardware_driver_canfd.dir/src/driver/motor_driver_impl.cpp.i
.PHONY : src/driver/motor_driver_impl.cpp.i

src/driver/motor_driver_impl.s: src/driver/motor_driver_impl.cpp.s
.PHONY : src/driver/motor_driver_impl.s

# target to generate assembly for a file
src/driver/motor_driver_impl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hardware_driver_canfd.dir/build.make CMakeFiles/hardware_driver_canfd.dir/src/driver/motor_driver_impl.cpp.s
.PHONY : src/driver/motor_driver_impl.cpp.s

src/interface/robot_hardware.o: src/interface/robot_hardware.cpp.o
.PHONY : src/interface/robot_hardware.o

# target to build an object file
src/interface/robot_hardware.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hardware_driver_canfd.dir/build.make CMakeFiles/hardware_driver_canfd.dir/src/interface/robot_hardware.cpp.o
.PHONY : src/interface/robot_hardware.cpp.o

src/interface/robot_hardware.i: src/interface/robot_hardware.cpp.i
.PHONY : src/interface/robot_hardware.i

# target to preprocess a source file
src/interface/robot_hardware.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hardware_driver_canfd.dir/build.make CMakeFiles/hardware_driver_canfd.dir/src/interface/robot_hardware.cpp.i
.PHONY : src/interface/robot_hardware.cpp.i

src/interface/robot_hardware.s: src/interface/robot_hardware.cpp.s
.PHONY : src/interface/robot_hardware.s

# target to generate assembly for a file
src/interface/robot_hardware.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hardware_driver_canfd.dir/build.make CMakeFiles/hardware_driver_canfd.dir/src/interface/robot_hardware.cpp.s
.PHONY : src/interface/robot_hardware.cpp.s

src/protocol/gripper_omnipicker_protocol.o: src/protocol/gripper_omnipicker_protocol.cpp.o
.PHONY : src/protocol/gripper_omnipicker_protocol.o

# target to build an object file
src/protocol/gripper_omnipicker_protocol.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hardware_driver_canfd.dir/build.make CMakeFiles/hardware_driver_canfd.dir/src/protocol/gripper_omnipicker_protocol.cpp.o
.PHONY : src/protocol/gripper_omnipicker_protocol.cpp.o

src/protocol/gripper_omnipicker_protocol.i: src/protocol/gripper_omnipicker_protocol.cpp.i
.PHONY : src/protocol/gripper_omnipicker_protocol.i

# target to preprocess a source file
src/protocol/gripper_omnipicker_protocol.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hardware_driver_canfd.dir/build.make CMakeFiles/hardware_driver_canfd.dir/src/protocol/gripper_omnipicker_protocol.cpp.i
.PHONY : src/protocol/gripper_omnipicker_protocol.cpp.i

src/protocol/gripper_omnipicker_protocol.s: src/protocol/gripper_omnipicker_protocol.cpp.s
.PHONY : src/protocol/gripper_omnipicker_protocol.s

# target to generate assembly for a file
src/protocol/gripper_omnipicker_protocol.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hardware_driver_canfd.dir/build.make CMakeFiles/hardware_driver_canfd.dir/src/protocol/gripper_omnipicker_protocol.cpp.s
.PHONY : src/protocol/gripper_omnipicker_protocol.cpp.s

src/protocol/motor_protocol.o: src/protocol/motor_protocol.cpp.o
.PHONY : src/protocol/motor_protocol.o

# target to build an object file
src/protocol/motor_protocol.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hardware_driver_canfd.dir/build.make CMakeFiles/hardware_driver_canfd.dir/src/protocol/motor_protocol.cpp.o
.PHONY : src/protocol/motor_protocol.cpp.o

src/protocol/motor_protocol.i: src/protocol/motor_protocol.cpp.i
.PHONY : src/protocol/motor_protocol.i

# target to preprocess a source file
src/protocol/motor_protocol.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hardware_driver_canfd.dir/build.make CMakeFiles/hardware_driver_canfd.dir/src/protocol/motor_protocol.cpp.i
.PHONY : src/protocol/motor_protocol.cpp.i

src/protocol/motor_protocol.s: src/protocol/motor_protocol.cpp.s
.PHONY : src/protocol/motor_protocol.s

# target to generate assembly for a file
src/protocol/motor_protocol.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hardware_driver_canfd.dir/build.make CMakeFiles/hardware_driver_canfd.dir/src/protocol/motor_protocol.cpp.s
.PHONY : src/protocol/motor_protocol.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... hardware_driver_uninstall"
	@echo "... uninstall"
	@echo "... example_event_motor_bus"
	@echo "... example_motor_callback"
	@echo "... example_motor_observer"
	@echo "... example_motor_zero_position"
	@echo "... hardware_driver_canfd"
	@echo "... examples/example_event_motor_bus.o"
	@echo "... examples/example_event_motor_bus.i"
	@echo "... examples/example_event_motor_bus.s"
	@echo "... examples/example_motor_callback.o"
	@echo "... examples/example_motor_callback.i"
	@echo "... examples/example_motor_callback.s"
	@echo "... examples/example_motor_observer.o"
	@echo "... examples/example_motor_observer.i"
	@echo "... examples/example_motor_observer.s"
	@echo "... examples/example_motor_zero_position.o"
	@echo "... examples/example_motor_zero_position.i"
	@echo "... examples/example_motor_zero_position.s"
	@echo "... src/bus/canfd_bus_impl.o"
	@echo "... src/bus/canfd_bus_impl.i"
	@echo "... src/bus/canfd_bus_impl.s"
	@echo "... src/driver/gripper_driver_impl.o"
	@echo "... src/driver/gripper_driver_impl.i"
	@echo "... src/driver/gripper_driver_impl.s"
	@echo "... src/driver/motor_driver_impl.o"
	@echo "... src/driver/motor_driver_impl.i"
	@echo "... src/driver/motor_driver_impl.s"
	@echo "... src/interface/robot_hardware.o"
	@echo "... src/interface/robot_hardware.i"
	@echo "... src/interface/robot_hardware.s"
	@echo "... src/protocol/gripper_omnipicker_protocol.o"
	@echo "... src/protocol/gripper_omnipicker_protocol.i"
	@echo "... src/protocol/gripper_omnipicker_protocol.s"
	@echo "... src/protocol/motor_protocol.o"
	@echo "... src/protocol/motor_protocol.i"
	@echo "... src/protocol/motor_protocol.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

