name: CI

on:
  push:
    branches: [ master, v1.0.0 ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libgtest-dev

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make -j$(nproc)

    - name: Test
      run: |
        cd build
        make test

    - name: Build example
      run: |
        cd build
        make simple_example

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: build/ 