name: CI

on:
  push:
    branches: [ master, v1.0.0 ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libgtest-dev libgmock-dev

    - name: Build library
      run: |
        mkdir build
        cd build
        cmake ..
        make -j$(nproc)

    - name: Build examples
      run: |
        cd build
        make -j$(nproc)
        ls -la examples/ || echo "No examples built"

    - name: Build tests with BUILD_TESTS=ON
      run: |
        cd build
        cmake -DBUILD_TESTS=ON ..
        make -j$(nproc)
        echo "Tests built successfully (not executed due to hardware requirements)"

    - name: Check build artifacts
      run: |
        echo "=== Library files ==="
        ls -la build/lib/ || echo "No lib directory"
        echo "=== Example files ==="
        ls -la build/examples/ || echo "No examples directory"
        echo "=== Test files ==="
        ls -la build/tests/ || echo "No tests directory"
        echo "Build completed successfully!"