name: CI

on:
  push:
    branches: [ master, v1.0.0 ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libgtest-dev libgmock-dev

    - name: Build library
      run: |
        mkdir build
        cd build
        cmake ..
        make -j$(nproc)

    - name: Build example
      run: |
        cd build
        make simple_example

    - name: Build tests (skip execution)
      run: |
        cd build
        make -j$(nproc)
        echo "Tests built successfully (not executed due to hardware requirements)"

    - name: Check library files
      run: |
        ls -la build/
        ls -la build/tests/ || echo "No tests directory"
        echo "Build completed successfully!"